// This file is auto-generated by TanStack Router at dev/build time.
// This stub satisfies tsc before the first `vite dev` run generates the real file.
/* eslint-disable */
// @ts-nocheck

import type { RouteManifest } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as AuthRoute } from './routes/_auth'
import { Route as AuthDashboardRoute } from './routes/_auth.dashboard'

const rootTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([AuthDashboardRoute]),
])

export const routeTree = rootTree

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: '/_auth'
      fullPath: '/_auth'
      preLoaderRoute: typeof AuthRoute
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRoute
      parentRoute: typeof AuthRoute
    }
  }
}
