/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthReviewRouteImport } from './routes/_auth.review'
import { Route as AuthPreviewRouteImport } from './routes/_auth.preview'
import { Route as AuthHistoryRouteImport } from './routes/_auth.history'
import { Route as AuthGenerateRouteImport } from './routes/_auth.generate'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthCorrectionExamIdRouteImport } from './routes/_auth.correction.$examId'

const AuthCorrectionExamIdRoute = AuthCorrectionExamIdRouteImport.update({
  id: '/correction/$examId',
  path: '/correction/$examId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReviewRoute = AuthReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPreviewRoute = AuthPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHistoryRoute = AuthHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGenerateRoute = AuthGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/generate': typeof AuthGenerateRoute
  '/history': typeof AuthHistoryRoute
  '/preview': typeof AuthPreviewRoute
  '/review': typeof AuthReviewRoute
  '/correction/$examId': typeof AuthCorrectionExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/generate': typeof AuthGenerateRoute
  '/history': typeof AuthHistoryRoute
  '/preview': typeof AuthPreviewRoute
  '/review': typeof AuthReviewRoute
  '/correction/$examId': typeof AuthCorrectionExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/generate': typeof AuthGenerateRoute
  '/_auth/history': typeof AuthHistoryRoute
  '/_auth/preview': typeof AuthPreviewRoute
  '/_auth/review': typeof AuthReviewRoute
  '/_auth/correction/$examId': typeof AuthCorrectionExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/generate'
    | '/history'
    | '/preview'
    | '/review'
    | '/correction/$examId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/generate' | '/history' | '/preview' | '/review' | '/correction/$examId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/dashboard'
    | '/_auth/generate'
    | '/_auth/history'
    | '/_auth/preview'
    | '/_auth/review'
    | '/_auth/correction/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/review': {
      id: '/_auth/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthReviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/preview': {
      id: '/_auth/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof AuthPreviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/history': {
      id: '/_auth/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthHistoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/generate': {
      id: '/_auth/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthGenerateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/correction/$examId': {
      id: '/_auth/correction/$examId'
      path: '/correction/$examId'
      fullPath: '/correction/$examId'
      preLoaderRoute: typeof AuthCorrectionExamIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthGenerateRoute: typeof AuthGenerateRoute
  AuthHistoryRoute: typeof AuthHistoryRoute
  AuthPreviewRoute: typeof AuthPreviewRoute
  AuthReviewRoute: typeof AuthReviewRoute
  AuthCorrectionExamIdRoute: typeof AuthCorrectionExamIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthGenerateRoute: AuthGenerateRoute,
  AuthHistoryRoute: AuthHistoryRoute,
  AuthPreviewRoute: AuthPreviewRoute,
  AuthReviewRoute: AuthReviewRoute,
  AuthCorrectionExamIdRoute: AuthCorrectionExamIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
