import type { User, Exam, Question, ExamWithQuestions } from '@teacher-exam/shared'

// ── Mock Teacher (current user) ─────────────────────────────────────────────

export const MOCK_TEACHER: User = {
  id: 'user-001',
  googleId: '117834920183847392',
  name: 'Sari Wulandari',
  email: 'sari.wulandari@sdnegeri1jakarta.sch.id',
  avatarUrl:
    'https://lh3.googleusercontent.com/a/ACg8ocI8FpzIwEmI4kJiKoKb5Y3XAvvNalQnfM3uQAX6XQ=s96-c',
  createdAt: '2026-04-01T07:00:00.000Z',
}

// ── 20 Bahasa Indonesia Questions for Kelas 6 ───────────────────────────────

const _MOCK_QUESTIONS = [
  // ── Pemahaman Bacaan (4 questions, q-001 to q-004) ──────────────────────
  {
    id: 'q-001',
    examId: 'exam-001',
    number: 1,
    text: 'Bacalah teks berikut!\n\n"Setiap pagi, Pak Hasan selalu menyiram tanaman di depan rumahnya sebelum berangkat kerja. Kebiasaan itu sudah dilakukannya selama dua puluh tahun. Tanaman-tanamannya tumbuh subur dan membuat lingkungan sekitar terlihat asri."\n\nPernyataan yang TEPAT berdasarkan teks di atas adalah ...',
    optionA: 'Kebiasaan Pak Hasan menjadikan lingkungan tampak indah dan asri',
    optionB: 'Pak Hasan menyiram tanaman setelah pulang kerja',
    optionC: 'Pak Hasan baru memulai kebiasaan menyiram tanaman tahun ini',
    optionD: 'Tanaman Pak Hasan sering layu karena jarang disiram',
    correctAnswer: 'a' as const,
    topic: 'Pemahaman Bacaan',
    difficulty: 'mudah',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:00:00.000Z',
  },
  {
    id: 'q-002',
    examId: 'exam-001',
    number: 2,
    text: 'Bacalah teks berikut!\n\n"Banjir yang melanda Desa Suka Makmur disebabkan oleh beberapa faktor. Pertama, curah hujan yang sangat tinggi selama tiga hari berturut-turut. Kedua, saluran air yang tersumbat oleh sampah warga. Ketiga, penebangan pohon di hulu sungai yang mengurangi daya serap air tanah."\n\nFaktor utama penyebab banjir yang berhubungan dengan perilaku masyarakat adalah ...',
    optionA: 'Saluran air tersumbat sampah dan penebangan pohon di hulu',
    optionB: 'Curah hujan yang sangat tinggi selama tiga hari',
    optionC: 'Letak desa yang berada di dataran rendah',
    optionD: 'Debit air sungai yang meningkat drastis',
    correctAnswer: 'a' as const,
    topic: 'Pemahaman Bacaan',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:00:00.000Z',
  },
  {
    id: 'q-003',
    examId: 'exam-001',
    number: 3,
    text: 'Bacalah teks berikut!\n\n"Perpustakaan sekolah kami baru saja mendapat tambahan ribuan buku baru. Namun, jumlah siswa yang berkunjung ke perpustakaan masih sangat sedikit. Kepala sekolah merasa prihatin dengan kondisi ini. Beliau berencana membuat program wajib kunjung perpustakaan setiap minggu."\n\nMengapa kepala sekolah membuat program wajib kunjung perpustakaan?',
    optionA: 'Karena koleksi buku perpustakaan sudah sangat banyak',
    optionB: 'Karena anggaran perpustakaan belum terpakai dengan baik',
    optionC: 'Karena sangat sedikit siswa yang memanfaatkan perpustakaan',
    optionD: 'Karena perpustakaan baru selesai direnovasi',
    correctAnswer: 'c' as const,
    topic: 'Pemahaman Bacaan',
    difficulty: 'mudah',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:00:00.000Z',
  },
  {
    id: 'q-004',
    examId: 'exam-001',
    number: 4,
    text: 'Bacalah teks berikut!\n\n"Daur ulang sampah plastik dapat memberikan manfaat ganda. Selain mengurangi pencemaran lingkungan, daur ulang juga menciptakan peluang usaha bagi masyarakat. Banyak pengusaha kecil yang berhasil meraup keuntungan dari bisnis daur ulang plastik menjadi produk bernilai jual tinggi."\n\nSimplan isi teks di atas yang paling tepat adalah ...',
    optionA: 'Daur ulang plastik hanya menguntungkan pengusaha besar',
    optionB: 'Sampah plastik tidak bisa diolah menjadi produk berguna',
    optionC: 'Pencemaran lingkungan disebabkan oleh industri daur ulang plastik',
    optionD: 'Daur ulang plastik bermanfaat bagi lingkungan sekaligus perekonomian',
    correctAnswer: 'd' as const,
    topic: 'Pemahaman Bacaan',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:01:00.000Z',
  },

  // ── Ide Pokok dan Gagasan Pendukung (3 questions, q-005 to q-007) ────────
  {
    id: 'q-005',
    examId: 'exam-001',
    number: 5,
    text: 'Bacalah teks berikut!\n\n"Komodo adalah hewan endemik yang hanya ditemukan di Pulau Komodo, Rinca, dan beberapa pulau kecil di Nusa Tenggara Timur. Hewan ini merupakan kadal terbesar di dunia dan dilindungi oleh pemerintah Indonesia. Pemerintah bahkan menjadikan habitatnya sebagai Taman Nasional Komodo."\n\nIde pokok paragraf di atas adalah ...',
    optionA: 'Komodo adalah hewan endemik yang dilindungi di kepulauan NTT',
    optionB: 'Komodo adalah kadal terbesar di dunia',
    optionC: 'Komodo hanya ditemukan di Pulau Komodo',
    optionD: 'Pemerintah mendirikan Taman Nasional Komodo',
    correctAnswer: 'a' as const,
    topic: 'Ide Pokok dan Gagasan Pendukung',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:02:00.000Z',
  },
  {
    id: 'q-006',
    examId: 'exam-001',
    number: 6,
    text: 'Perhatikan kalimat-kalimat berikut!\n\n(1) Olahraga secara teratur sangat penting bagi kesehatan tubuh.\n(2) Dengan berolahraga, jantung menjadi lebih kuat dan stamina meningkat.\n(3) Olahraga juga membantu menjaga berat badan ideal.\n(4) Selain itu, olahraga dapat mengurangi risiko berbagai penyakit kronis.\n\nKalimat utama paragraf tersebut adalah kalimat nomor ...',
    optionA: 'Kalimat (2)',
    optionB: 'Kalimat (3)',
    optionC: 'Kalimat (4)',
    optionD: 'Kalimat (1)',
    correctAnswer: 'd' as const,
    topic: 'Ide Pokok dan Gagasan Pendukung',
    difficulty: 'mudah',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:03:00.000Z',
  },
  {
    id: 'q-007',
    examId: 'exam-001',
    number: 7,
    text: 'Bacalah paragraf berikut!\n\n"Penggunaan gadget yang berlebihan pada anak-anak menimbulkan berbagai dampak negatif. Anak-anak menjadi malas bergerak dan bersosialisasi secara langsung. Kemampuan berkonsentrasi pun menurun karena terbiasa dengan stimulus yang cepat berganti. Bahkan, gangguan tidur sering dialami anak yang terlalu lama menatap layar."\n\nGagasan pendukung dalam paragraf tersebut adalah ...',
    optionA: 'Gadget menyebabkan anak malas, sulit konsentrasi, dan gangguan tidur',
    optionB: 'Penggunaan gadget berlebihan berdampak negatif bagi anak',
    optionC: 'Anak-anak harus dilarang menggunakan gadget sepenuhnya',
    optionD: 'Orang tua harus memantau penggunaan gadget anak setiap saat',
    correctAnswer: 'a' as const,
    topic: 'Ide Pokok dan Gagasan Pendukung',
    difficulty: 'sulit',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:04:00.000Z',
  },

  // ── Unsur Intrinsik Cerita (3 questions, q-008 to q-010) ────────────────
  {
    id: 'q-008',
    examId: 'exam-001',
    number: 8,
    text: 'Bacalah penggalan cerita berikut!\n\n"Rima berjalan gontai memasuki ruang kelas. Nilai ulangannya jauh di bawah teman-temannya. Namun ia tidak putus asa. Setiap malam ia belajar lebih keras dari sebelumnya. Dua bulan kemudian, Rima berhasil meraih nilai tertinggi di kelas."\n\nAmanat yang terkandung dalam cerita tersebut adalah ...',
    optionA: 'Kita harus selalu mendapat nilai tertinggi di kelas',
    optionB: 'Kegagalan adalah akhir dari segalanya',
    optionC: 'Belajar hanya perlu dilakukan menjelang ulangan',
    optionD: 'Ketekunan dan kerja keras dapat mengubah kegagalan menjadi keberhasilan',
    correctAnswer: 'd' as const,
    topic: 'Unsur Intrinsik Cerita',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:05:00.000Z',
  },
  {
    id: 'q-009',
    examId: 'exam-001',
    number: 9,
    text: 'Perhatikan kutipan cerita berikut!\n\n"Di sebuah desa kecil di kaki gunung, hiduplah seorang petani bernama Darso. Setiap hari ia menggarap sawahnya dengan penuh semangat meski musim kemarau panjang melanda. Ia tidak pernah mengeluh kepada siapapun."\n\nLatar tempat dalam kutipan cerita di atas adalah ...',
    optionA: 'Di pinggir pantai yang sepi',
    optionB: 'Di tengah hutan yang lebat',
    optionC: 'Di kota besar yang ramai',
    optionD: 'Di sebuah desa kecil di kaki gunung',
    correctAnswer: 'd' as const,
    topic: 'Unsur Intrinsik Cerita',
    difficulty: 'mudah',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:06:00.000Z',
  },
  {
    id: 'q-010',
    examId: 'exam-001',
    number: 10,
    text: 'Bacalah kutipan cerita berikut!\n\n"Saat semua teman berlari menghindari hujan, Bagas justru tetap berdiri di halaman sekolah membantu Bu Guru yang menjatuhkan buku-bukunya. Ia tidak peduli bajunya basah kuyup. Teman-temannya heran melihat sikap Bagas."\n\nWatak tokoh Bagas dalam cerita tersebut adalah ...',
    optionA: 'Penakut dan pemalu',
    optionB: 'Penolong dan rela berkorban',
    optionC: 'Sombong dan keras kepala',
    optionD: 'Pemalas dan tidak peduli',
    correctAnswer: 'b' as const,
    topic: 'Unsur Intrinsik Cerita',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:07:00.000Z',
  },

  // ── Kosakata: Denotatif, Konotatif, Kiasan (3 questions, q-011 to q-013) ─
  {
    id: 'q-011',
    examId: 'exam-001',
    number: 11,
    text: 'Perhatikan kalimat berikut!\n\n"Prestasi Andi di bidang akademik membuat nama baik sekolah harum di tingkat nasional."\n\nMakna kata "harum" dalam kalimat di atas adalah ...',
    optionA: 'Mengeluarkan bau yang sedap seperti bunga',
    optionB: 'Wangi karena memakai parfum mahal',
    optionC: 'Terkenal dan mendapat pujian yang baik',
    optionD: 'Bersih dan terawat dengan baik',
    correctAnswer: 'c' as const,
    topic: 'Kosakata (Denotatif, Konotatif, Kiasan)',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:08:00.000Z',
  },
  {
    id: 'q-012',
    examId: 'exam-001',
    number: 12,
    text: 'Perhatikan kalimat berikut!\n\n"Dia adalah tangan kanan kepala sekolah dalam mengurusi kegiatan ekstrakurikuler."\n\nMakna frasa "tangan kanan" dalam kalimat di atas adalah ...',
    optionA: 'Pembantu utama yang dipercaya dan diandalkan',
    optionB: 'Orang yang suka menggunakan tangan kanan',
    optionC: 'Orang yang bekerja di sebelah kanan',
    optionD: 'Asisten yang sering melakukan kesalahan',
    correctAnswer: 'a' as const,
    topic: 'Kosakata (Denotatif, Konotatif, Kiasan)',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:09:00.000Z',
  },
  {
    id: 'q-013',
    examId: 'exam-001',
    number: 13,
    text: 'Manakah kalimat yang menggunakan kata dengan makna denotatif?',
    optionA: 'Adik adalah buah hati ayah dan ibu',
    optionB: 'Ia memiliki otak yang encer sehingga mudah memahami pelajaran',
    optionC: 'Petani itu menggarap ladang di lereng bukit',
    optionD: 'Guru itu dianggap sebagai penerang dalam kegelapan',
    correctAnswer: 'c' as const,
    topic: 'Kosakata (Denotatif, Konotatif, Kiasan)',
    difficulty: 'sulit',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:10:00.000Z',
  },

  // ── Teks Eksplanasi (3 questions, q-014 to q-016) ───────────────────────
  {
    id: 'q-014',
    examId: 'exam-001',
    number: 14,
    text: 'Bacalah teks berikut!\n\n"Gempa bumi terjadi akibat pergerakan lempeng tektonik di dalam bumi. Ketika dua lempeng bertumbukan atau bergesekan, energi yang tersimpan dilepaskan secara tiba-tiba dalam bentuk gelombang seismik. Gelombang inilah yang kita rasakan sebagai guncangan di permukaan bumi."\n\nTeks di atas termasuk jenis teks ...',
    optionA: 'Teks narasi karena menceritakan urutan kejadian',
    optionB: 'Teks persuasi karena mengajak pembaca untuk waspada',
    optionC: 'Teks eksplanasi karena menjelaskan proses terjadinya gempa bumi',
    optionD: 'Teks deskripsi karena menggambarkan keadaan bumi',
    correctAnswer: 'c' as const,
    topic: 'Teks Eksplanasi',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:11:00.000Z',
  },
  {
    id: 'q-015',
    examId: 'exam-001',
    number: 15,
    text: 'Perhatikan struktur teks eksplanasi berikut!\n\n(1) Proses terjadinya pelangi\n(2) Interpretasi — pelangi adalah fenomena alam yang indah\n(3) Pernyataan umum — pelangi adalah fenomena optik\n\nUrutan struktur teks eksplanasi yang tepat adalah ...',
    optionA: '(1), (2), (3)',
    optionB: '(3), (1), (2)',
    optionC: '(2), (3), (1)',
    optionD: '(3), (2), (1)',
    correctAnswer: 'b' as const,
    topic: 'Teks Eksplanasi',
    difficulty: 'sulit',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:12:00.000Z',
  },
  {
    id: 'q-016',
    examId: 'exam-001',
    number: 16,
    text: 'Bacalah penggalan teks eksplanasi berikut!\n\n"Proses fotosintesis terjadi di dalam kloroplas daun. Tumbuhan menyerap cahaya matahari melalui klorofil. Energi cahaya tersebut digunakan untuk mengubah air dan karbon dioksida menjadi glukosa dan oksigen."\n\nCiri kebahasaan yang menunjukkan teks tersebut adalah teks eksplanasi adalah ...',
    optionA: 'Menggunakan kata ganti orang pertama seperti "saya" dan "kami"',
    optionB: 'Menggunakan kata-kata yang bersifat ajakan dan larangan',
    optionC: 'Menggunakan banyak kalimat langsung dan dialog',
    optionD: 'Menggunakan kata hubung kausal seperti "karena" dan "sehingga"',
    correctAnswer: 'd' as const,
    topic: 'Teks Eksplanasi',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:13:00.000Z',
  },

  // ── Gaya Bahasa / Majas (2 questions, q-017 to q-018) ───────────────────
  {
    id: 'q-017',
    examId: 'exam-001',
    number: 17,
    text: 'Perhatikan kalimat berikut!\n\n"Angin berbisik lembut di antara dedaunan pohon bambu."\n\nKalimat tersebut menggunakan majas ...',
    optionA: 'Hiperbola, karena melebih-lebihkan sesuatu',
    optionB: 'Personifikasi, karena memberikan sifat manusia pada benda mati',
    optionC: 'Simile, karena membandingkan dua hal dengan kata "seperti"',
    optionD: 'Metafora, karena membandingkan secara langsung tanpa kata pembanding',
    correctAnswer: 'b' as const,
    topic: 'Gaya Bahasa / Majas',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:14:00.000Z',
  },
  {
    id: 'q-018',
    examId: 'exam-001',
    number: 18,
    text: 'Kalimat mana yang menggunakan majas hiperbola?',
    optionA: 'Matanya sebening embun pagi yang menetes di atas daun',
    optionB: 'Ia berlari secepat kilat hingga menembus langit',
    optionC: 'Air matanya mengalir deras bagai sungai tak terbendung',
    optionD: 'Suaranya seperti alunan musik yang merdu',
    correctAnswer: 'b' as const,
    topic: 'Gaya Bahasa / Majas',
    difficulty: 'sulit',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:15:00.000Z',
  },

  // ── Tanda Baca dan Ejaan (2 questions, q-019 to q-020) ──────────────────
  {
    id: 'q-019',
    examId: 'exam-001',
    number: 19,
    text: 'Penulisan kalimat yang TEPAT sesuai kaidah ejaan bahasa Indonesia adalah ...',
    optionA: '"Kami berencana pergi ke Bandung, Jawa Barat, pada bulan juni."',
    optionB: '"kami berencana pergi ke bandung, jawa barat, pada bulan Juni."',
    optionC: '"Kami berencana pergi ke Bandung, Jawa Barat, pada bulan Juni."',
    optionD: '"Kami berencana pergi ke bandung, Jawa barat, pada bulan Juni."',
    correctAnswer: 'c' as const,
    topic: 'Tanda Baca dan Ejaan',
    difficulty: 'mudah',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:16:00.000Z',
  },
  {
    id: 'q-020',
    examId: 'exam-001',
    number: 20,
    text: 'Perhatikan kalimat berikut!\n\n"Ibu membeli apel jeruk dan mangga di pasar."\n\nPenulisan kalimat di atas kurang tepat karena ...',
    optionA: 'Tidak ada tanda tanya di akhir kalimat',
    optionB: 'Tidak menggunakan tanda koma untuk memisahkan unsur dalam perincian',
    optionC: 'Kata "Ibu" seharusnya ditulis dengan huruf kecil',
    optionD: 'Kata "pasar" seharusnya ditulis dengan huruf kapital',
    correctAnswer: 'b' as const,
    topic: 'Tanda Baca dan Ejaan',
    difficulty: 'sedang',
    status: 'accepted' as const,
    validationStatus: 'valid' as const,
    validationReason: null,
    createdAt: '2026-04-22T08:17:00.000Z',
  },
]

export const MOCK_QUESTIONS = _MOCK_QUESTIONS as unknown as Question[]

// ── Exam fixtures ────────────────────────────────────────────────────────────

const _MOCK_EXAM_FINAL = {
  id: 'exam-001',
  userId: 'user-001',
  title: 'TKA Bahasa Indonesia Kelas 6',
  subject: 'bahasa_indonesia' as const,
  grade: 6,
  difficulty: 'campuran' as const,
  topic: 'Pemahaman Bacaan',
  reviewMode: 'fast' as const,
  status: 'final' as const,
  schoolName: 'SD Negeri 1 Jakarta',
  academicYear: '2025/2026',
  examType: 'TKA',
  examDate: '2026-04-22',
  durationMinutes: 60,
  instructions:
    "Bacalah do'a sebelum mengerjakan soal.\nKerjakan soal yang mudah terlebih dahulu.\nBekerjalah dengan jujur dan mandiri.",
  classContext: null,
  discussionMd: null,
  createdAt: '2026-04-22T08:00:00.000Z',
  updatedAt: '2026-04-22T09:00:00.000Z',
}

const _MOCK_EXAM_DRAFT = {
  id: 'exam-002',
  userId: 'user-001',
  title: 'UTS Pendidikan Pancasila Kelas 5',
  subject: 'pendidikan_pancasila' as const,
  grade: 5,
  difficulty: 'sedang' as const,
  topic: 'Nilai-nilai Pancasila',
  reviewMode: 'slow' as const,
  status: 'draft' as const,
  schoolName: 'SD Negeri 1 Jakarta',
  academicYear: '2025/2026',
  examType: 'UTS',
  examDate: '2026-05-05',
  durationMinutes: 60,
  instructions:
    "Bacalah do'a sebelum mengerjakan soal.\nIsilah identitasmu dengan lengkap dan jelas.\nKerjakan soal dengan teliti.",
  classContext: 'Kelas 5A dan 5B digabung untuk ujian bersama.',
  discussionMd: null,
  createdAt: '2026-04-18T10:00:00.000Z',
  updatedAt: '2026-04-18T11:30:00.000Z',
}

const _MOCK_EXAM_HISTORY = {
  id: 'exam-003',
  userId: 'user-001',
  title: 'Ulangan Harian — Kelas 5',
  subject: 'bahasa_indonesia' as const,
  grade: 5,
  difficulty: 'mudah' as const,
  topic: 'Teks Deskripsi, Kosakata',
  reviewMode: 'fast' as const,
  status: 'final' as const,
  schoolName: 'SD Negeri 1 Jakarta',
  academicYear: '2025/2026',
  examType: 'Ulangan Harian',
  examDate: '2026-04-15',
  durationMinutes: 45,
  instructions: "Kerjakan soal dengan teliti.",
  classContext: null,
  discussionMd: null,
  createdAt: '2026-04-15T08:00:00.000Z',
  updatedAt: '2026-04-15T09:00:00.000Z',
}

export const MOCK_EXAM_FINAL = _MOCK_EXAM_FINAL as unknown as Exam
export const MOCK_EXAM_DRAFT = _MOCK_EXAM_DRAFT as unknown as Exam
export const MOCK_EXAM_HISTORY = _MOCK_EXAM_HISTORY as unknown as Exam

const _MOCK_EXAM_HISTORY_EXTRA = [
  {
    id: 'exam-004',
    userId: 'user-001',
    title: 'PTS Pendidikan Pancasila Kelas 6',
    subject: 'pendidikan_pancasila' as const,
    grade: 6,
    difficulty: 'campuran' as const,
    topic: 'Hak dan Kewajiban Warga Negara',
    reviewMode: 'fast' as const,
    status: 'final' as const,
    schoolName: 'SD Negeri 1 Jakarta',
    academicYear: '2025/2026',
    examType: 'PTS',
    examDate: '2026-04-08',
    durationMinutes: 60,
    instructions: "Bacalah do'a sebelum mengerjakan soal.\nKerjakan soal dengan teliti.",
    classContext: null,
    discussionMd: null,
    createdAt: '2026-04-08T07:30:00.000Z',
    updatedAt: '2026-04-08T08:30:00.000Z',
  },
  {
    id: 'exam-005',
    userId: 'user-001',
    title: 'Ulangan Harian Tema 7 — Kelas 5',
    subject: 'bahasa_indonesia' as const,
    grade: 5,
    difficulty: 'mudah' as const,
    topic: 'Teks Narasi',
    reviewMode: 'fast' as const,
    status: 'final' as const,
    schoolName: 'SD Negeri 1 Jakarta',
    academicYear: '2025/2026',
    examType: 'Ulangan Harian',
    examDate: '2026-04-02',
    durationMinutes: 45,
    instructions: 'Kerjakan soal dengan teliti. Jangan mencontek.',
    classContext: null,
    discussionMd: null,
    createdAt: '2026-04-02T09:00:00.000Z',
    updatedAt: '2026-04-02T09:50:00.000Z',
  },
  {
    id: 'exam-006',
    userId: 'user-001',
    title: 'Asesmen Sumatif PPKN Kelas 6',
    subject: 'pendidikan_pancasila' as const,
    grade: 6,
    difficulty: 'sedang' as const,
    topic: 'Bhinneka Tunggal Ika',
    reviewMode: 'slow' as const,
    status: 'draft' as const,
    schoolName: 'SD Negeri 1 Jakarta',
    academicYear: '2025/2026',
    examType: 'Asesmen Sumatif',
    examDate: '2026-05-12',
    durationMinutes: 60,
    instructions: 'Bacalah perintah pada setiap soal dengan teliti.',
    classContext: 'Penilaian akhir tema untuk Kelas 6A.',
    discussionMd: null,
    createdAt: '2026-03-28T10:15:00.000Z',
    updatedAt: '2026-03-28T11:00:00.000Z',
  },
  {
    id: 'exam-007',
    userId: 'user-001',
    title: 'Latihan Soal Bahasa Indonesia Kelas 5',
    subject: 'bahasa_indonesia' as const,
    grade: 5,
    difficulty: 'sedang' as const,
    topic: 'Kosakata Baru dan Sinonim',
    reviewMode: 'fast' as const,
    status: 'final' as const,
    schoolName: 'SD Negeri 1 Jakarta',
    academicYear: '2025/2026',
    examType: 'Latihan',
    examDate: '2026-03-22',
    durationMinutes: 30,
    instructions: 'Latihan mandiri sebelum ulangan tema berikutnya.',
    classContext: null,
    discussionMd: null,
    createdAt: '2026-03-22T08:45:00.000Z',
    updatedAt: '2026-03-22T09:25:00.000Z',
  },
  {
    id: 'exam-008',
    userId: 'user-001',
    title: 'PTS Bahasa Indonesia Kelas 6',
    subject: 'bahasa_indonesia' as const,
    grade: 6,
    difficulty: 'sulit' as const,
    topic: 'Teks Eksplanasi dan Majas',
    reviewMode: 'slow' as const,
    status: 'final' as const,
    schoolName: 'SD Negeri 1 Jakarta',
    academicYear: '2025/2026',
    examType: 'PTS',
    examDate: '2026-03-15',
    durationMinutes: 90,
    instructions: 'Penilaian Tengah Semester. Kerjakan secara mandiri.',
    classContext: null,
    discussionMd: null,
    createdAt: '2026-03-15T07:00:00.000Z',
    updatedAt: '2026-03-15T08:30:00.000Z',
  },
  {
    id: 'exam-009',
    userId: 'user-001',
    title: 'Ulangan Harian PPKN Kelas 5',
    subject: 'pendidikan_pancasila' as const,
    grade: 5,
    difficulty: 'mudah' as const,
    topic: 'Norma di Lingkungan Sekitar',
    reviewMode: 'fast' as const,
    status: 'draft' as const,
    schoolName: 'SD Negeri 1 Jakarta',
    academicYear: '2025/2026',
    examType: 'Ulangan Harian',
    examDate: '2026-05-02',
    durationMinutes: 45,
    instructions: 'Bacalah dengan teliti sebelum menjawab.',
    classContext: null,
    discussionMd: null,
    createdAt: '2026-03-10T09:30:00.000Z',
    updatedAt: '2026-03-10T10:10:00.000Z',
  },
] as const

export const MOCK_EXAM_HISTORY_EXTRA = _MOCK_EXAM_HISTORY_EXTRA as unknown as Exam[]

export const MOCK_DASHBOARD_STATS = {
  totalSheets: 8,
  finalCount: 5,
  draftCount: 3,
} as const

export const MOCK_WEEKLY_ACTIVITY = [
  { day: 'Rab', count: 2, variant: 'default' as const },
  { day: 'Kam', count: 4, variant: 'default' as const },
  { day: 'Jum', count: 3, variant: 'secondary' as const },
  { day: 'Sab', count: 6, variant: 'default' as const },
  { day: 'Min', count: 1, variant: 'default' as const },
  { day: 'Sen', count: 5, variant: 'secondary' as const },
  { day: 'Sel', count: 7, variant: 'default' as const },
] as const

// ── Exam with questions ──────────────────────────────────────────────────────

export const MOCK_EXAM_WITH_QUESTIONS: ExamWithQuestions = {
  ...MOCK_EXAM_FINAL,
  questions: MOCK_QUESTIONS,
} as unknown as ExamWithQuestions

// ── Student names for grading simulation ────────────────────────────────────

export const MOCK_STUDENTS: string[] = [
  'Ani Wijaya',
  'Budi Santoso',
  'Citra Dewi',
  'Dian Pratama',
  'Eko Raharjo',
  'Fitri Handayani',
  'Galih Nugroho',
  'Hana Kusuma',
  'Irfan Maulana',
  'Juwita Sari',
]

// ── Helper functions ─────────────────────────────────────────────────────────

export function getMockExams(): Exam[] {
  return [MOCK_EXAM_FINAL, MOCK_EXAM_DRAFT, MOCK_EXAM_HISTORY]
}

/**
 * Returns the full Riwayat Ujian dataset, sorted newest first by createdAt.
 * Used by the /history route as the source of mock exam rows.
 */
export function getMockExamHistory(): Exam[] {
  const all: Exam[] = [
    MOCK_EXAM_FINAL,
    MOCK_EXAM_DRAFT,
    MOCK_EXAM_HISTORY,
    ...MOCK_EXAM_HISTORY_EXTRA,
  ]
  return [...all].sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
  )
}

export function getMockExamWithQuestions(id: string): ExamWithQuestions | undefined {
  if (id === 'exam-001') return MOCK_EXAM_WITH_QUESTIONS
  return undefined
}
